### ISSUE TITLE
Errors while importing x264.ini config file with "configparser"

### ISSUE THREAD

**Issue by Mshriver2** [Mshriver2/pyAutoEncode#5]
This is the error being generated when the first imported value is attempted to be assigned to a variable. This starts on line 42. It may be that the .ini file is not correct or may be missing some code for configparser.

`Traceback (most recent call last):
  File ".\encode.py", line 42, in <module>
    c_threads = x264_config.get('x264', 'cfg_threads')
  File "C:\Python27\lib\site-packages\backports\configparser\__init__.py", line 858, in get
    d = self._unify_values(section, vars)
  File "C:\Python27\lib\site-packages\backports\configparser\__init__.py", line 1228, in _unify_values
    raise NoSectionError(section)
backports.configparser.NoSectionError: No section: 'x264'`

**Comment by sd31117** [comment]
closed commit/ca36591b2cb0ba3d5271c2d99403b71ea69baf2c
